### ISSUE TITLE
Can you explain how did you got the high score in link prediction task?

### ISSUE THREAD

**Issue by SeongJinAhn** [graph-star-team/graph_star#5]
Can you explain how did you got the high score in link prediction task in cora dataset?

I tried the parameters with which you wrote down but I only got  MAX LP AVG about 0.9 in epoch 10000...

**Comment by luhaonan20** [comment]
hi, please add below two line in run_lp.py,
args.residual = True
args.residual_star = True

Or update your code with the newest version with new commend

**Comment by SeongJinAhn** [comment]
Thank you!
