### ISSUE TITLE
question on node classification results 

### ISSUE THREAD

**Issue by amblee0306** [graph-star-team/graph_star#8]
Hi there, I would like to ask if the hyperparameters for other models i.e. GCN, GAT, are of those mentioned on their papers (for cora dataset)? Since for graphstar, I believe the L2 reg, lr and dropouts are different from those.

**Comment by luhaonan20** [comment]
Hi, the result for GCN, GAT are taken from their original papers, our hyperparameters are indeed different from them (As we given in our readme part :)

**Comment by luhaonan20** [comment]
> Hi there, I would like to ask if the hyperparameters for other models i.e. GCN, GAT, are of those mentioned on their papers (for cora dataset)? Since for graphstar, I believe the L2 reg, lr and dropouts are different from those.

**Comment by luhaonan20** [comment]
> Hi there, I would like to ask if the hyperparameters for other models i.e. GCN, GAT, are of those mentioned on their papers (for cora dataset)? Since for graphstar, I believe the L2 reg, lr and dropouts are different from those.

Hi, the result for GCN, GAT are taken from their original papers, our hyperparameters are indeed different from them (As we given in our readme part :)

**Comment by amblee0306** [comment]
Thanks
